### ISSUE TITLE
Am I typing this wrong, it does not appear to work

### ISSUE THREAD

**Issue by valadas** [jorelius/Watch#2]
I am typing this:
`watch FileSystem -TargetProgram docfx -Arguments "--serve" -Path "D:\websites\990\Website\DesktopModules\Contacts\docfx_project\"`

And I get that:
`Press Key to End`

However I don't see `docfx --serve` running either initially or after I change a file in that folder...

Am I doing it wrong ?

**Comment by jorelius** [comment]
You will need to update and remove the trailing slash from the path. I put in an update that should help with your issue.

**Comment by valadas** [comment]
Excellent, that worked. Now the other issue is it does not kill the previous process and fire up a new one. But it did solve the issue with the update and removing the last `\` 

I switched to npm-watch because of the not killing the old process thing, but other than that this is a great utility for next time I need something that does not need to kill the other process.

Thanks.
